version: 2.1

workflows:
  workflow:
    jobs:
      - job

jobs:
  job:
    docker:
      - image: alpine
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'f8:43:c1:db:6f:04:b4:fc:58:38:20:f0:89:e5:5e:9b'
      - run: ls -lR ~/.ssh
      - run: cat ~/.ssh/config
